import type { Product } from "./types"

export const products: Product[] = [
  // Perros
  {
    id: "p1",
    name: "Alimento Premium para Perros",
    price: 180,
    category: "perros",
    image: "/premium-dog-food-bag.png",
    description: "Alimento balanceado de alta calidad para perros adultos",
  },
  {
    id: "p2",
    name: "Alimento Cachorro",
    price: 195,
    category: "perros",
    image: "/puppy-food-bag.png",
    description: "Nutrición especial para cachorros en crecimiento",
  },
  {
    id: "p3",
    name: "Snacks Dentales",
    price: 45,
    category: "perros",
    image: "/dog-dental-treats.jpg",
    description: "Premios que cuidan la salud dental de tu perro",
  },
  {
    id: "p4",
    name: "Hueso de Juguete",
    price: 35,
    category: "perros",
    image: "/dog-toy-bone.jpg",
    description: "Juguete resistente para masticar",
  },
  // Gatos
  {
    id: "g1",
    name: "Alimento Premium para Gatos",
    price: 165,
    category: "gatos",
    image: "/premium-cat-food-bag.jpg",
    description: "Alimento completo para gatos adultos",
  },
  {
    id: "g2",
    name: "Arena Aglomerante",
    price: 85,
    category: "gatos",
    image: "/cat-litter-bag.jpg",
    description: "Arena sanitaria de alta absorción",
  },
  {
    id: "g3",
    name: "Rascador para Gatos",
    price: 120,
    category: "gatos",
    image: "/cat-scratching-post.png",
    description: "Torre rascadora con plataformas",
  },
  {
    id: "g4",
    name: "Juguete Ratón",
    price: 25,
    category: "gatos",
    image: "/cat-toy-mouse.jpg",
    description: "Juguete interactivo para gatos",
  },
  // Higiene
  {
    id: "h1",
    name: "Shampoo para Perros",
    price: 55,
    category: "higiene",
    image: "/dog-shampoo-bottle.png",
    description: "Shampoo hipoalergénico con acondicionador",
  },
  {
    id: "h2",
    name: "Cepillo Deslanador",
    price: 65,
    category: "higiene",
    image: "/pet-deshedding-brush.jpg",
    description: "Elimina el pelo muerto eficazmente",
  },
  {
    id: "h3",
    name: "Cortauñas Profesional",
    price: 45,
    category: "higiene",
    image: "/pet-nail-clipper.jpg",
    description: "Cortauñas de acero inoxidable",
  },
  {
    id: "h4",
    name: "Toallitas Húmedas",
    price: 35,
    category: "higiene",
    image: "/pet-wet-wipes.jpg",
    description: "Toallitas de limpieza para mascotas",
  },
  // Accesorios
  {
    id: "a1",
    name: "Collar Ajustable",
    price: 40,
    category: "accesorios",
    image: "/adjustable-dog-collar.jpg",
    description: "Collar resistente con hebilla de seguridad",
  },
  {
    id: "a2",
    name: "Correa Retráctil",
    price: 95,
    category: "accesorios",
    image: "/retractable-dog-leash.jpg",
    description: "Correa extensible hasta 5 metros",
  },
  {
    id: "a3",
    name: "Cama Acolchada",
    price: 180,
    category: "accesorios",
    image: "/pet-cushion-bed.jpg",
    description: "Cama suave y lavable para mascotas",
  },
  {
    id: "a4",
    name: "Comedero Doble",
    price: 55,
    category: "accesorios",
    image: "/double-pet-bowl.jpg",
    description: "Comedero y bebedero de acero inoxidable",
  },
]
